repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        language_version: python3
        args: [--line-length, &line_length "120"]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args:
          [
            --profile=black,
            --check-only,
            --line-length,
            *line_length,
            --project,
            KNOWN_FIRST_PARTY=doing,
          ]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--max-line-length, *line_length, "--ignore=D100,D104,W503"]
  # D100 requires all Python files (modules) to have a "public" docstring even if all functions within have a docstring.
  # D104 requires __init__ files to have a docstring
  # W503 line break before binary operator (for compatibility with black)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args: [--namespace-packages, --show-error-codes, --pretty]
        additional_dependencies:
          [
            "types-PyYAML",
            "types-click",
            "types-psutil",
            "pytest",
            "pytest-mock",
            "rich",
          ]
