
site_name: ING Azure DevOps CLI
site_description: 'Speed up work with INGs Azure Devops'
edit_uri: ''
copyright: 'Copyright &copy; 2020 ING'

theme:
    name: material
    palette:
        primary: white
    font: false
    icon:
        logo: octicons/terminal-16
    favicon: assets/images/cli.png
    features:
        - tabs
        - instant

nav:
  - index.md
  - Getting started:
    - get_started/install.md
    - get_started/setup_auth.md
    - get_started/setup_project.md
  - How to:
    - howto/getting_started.md
  - Reference:
    - reference/reference.md
  - contributing.md


markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
          options:
              custom_icons:
                  - site/overrides/.icons
