
site_name: doing CLI for Azure DevOps
site_description: 'Speed up work with Azure Devops'
edit_uri: ''
copyright: 'Copyright &copy; 2021'
repo_url: https://github.com/timvink/doing-cli

theme:
    name: material
    palette:
        primary: white
        accent: deep orange
        scheme: preference
    font: false
    icon:
        logo: octicons/terminal-16
    favicon: assets/images/cli.png
    features:
        - navigation.tracking
        - header.autohide
        - navigation.tabs

nav:
  - index.md
  - Getting started:
    - get_started/install.md
    - get_started/setup_auth.md
    - get_started/setup_project.md
  - How to:
    - Workflow new issues: howto/workflow_new_item.md
    - Workflow existing issues: howto/workflow_existing_item.md
    - Workflow sprints: howto/workflow_sprints.md
    - Workflows with envvars: howto/workflow_envvars.md
    - Python scripting: howto/python_scripting.md
    - Shell completion: howto/command_completion.md
    - Connection problems: howto/connection_problems.md
  - Commands:
    - .doing-cli-config.yml: reference/config_file.md
    - init: reference/manual/init.md
    - create:
      - issue: reference/manual/create_issue.md
      - pr: reference/manual/create_pr.md
    - list: reference/manual/list.md
    - open: reference/manual/open.md
    - workon: reference/manual/workon.md
    - close:
      - issue: reference/manual/close_issue.md
      - pr: reference/manual/close_pr.md
  - Discussion:
    - One Project Setup: discussion/oneproject_setup.md
    - contributing.md

plugins:
  - macros:
        module_name: src/doing/utils

markdown_extensions:
    - abbr
    - admonition
    - pymdownx.keys
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
          options:
              custom_icons:
                  - site/overrides/.icons
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
    - 'https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js'
    - 'assets/js/termynal.js'
    - 'assets/js/custom.js'

extra_css:
    - 'assets/css/termynal.css'
    - 'assets/css/custom.css'
