
site_name: doing CLI for Azure DevOps
site_description: 'Speed up work with INGs Azure Devops'
edit_uri: ''
copyright: 'Copyright &copy; 2020 ING'

theme:
    name: material
    palette:
        primary: white
    font: false
    icon:
        logo: octicons/terminal-16
    favicon: assets/images/cli.png
    features:
        - tabs
        - instant

nav:
  - index.md
  - Getting started:
    - get_started/install.md
    - get_started/setup_auth.md
    - get_started/setup_project.md
  - How to:
    - Workflow new issues: howto/workflow_new_item.md
    - Workflow existing issues: howto/workflow_existing_item.md
    - Workflow sprints: howto/workflow_sprints.md
    - Connection problems: howto/connection_problems.md
  - Reference:
    - Config File: reference/config_file.md
    - reference/commands.md
  - Discussion:
    - discussion/oneproject_setup.md
  - contributing.md


markdown_extensions:
    - abbr
    - admonition
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
          options:
              custom_icons:
                  - site/overrides/.icons
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
    - 'https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js'
    - 'assets/js/termynal.js'
    - 'assets/js/custom.js'

extra_css:
    - 'assets/css/termynal.css'
    - 'assets/css/custom.css'
