
site_name: doing CLI for Azure DevOps
site_description: 'Speed up work with Azure Devops'
edit_uri: ''
copyright: 'Copyright &copy; 2021'
repo_url: https://github.com/ing-bank/doing-cli
site_url: 'https://ing-bank.github.io/doing-cli/'

theme:
    name: material
    palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: white
        accent: deep orange
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode

      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: deep orange
        accent: deep orange
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode

    font: false
    icon:
        logo: octicons/terminal-16
        repo: fontawesome/brands/github
    favicon: assets/images/cli.png
    features:
        - navigation.tracking
        - navigation.sections
        - header.autohide
        - navigation.tabs
        - navigation.top

nav:
  - index.md
  - Getting started:
    - get_started/install.md
    - get_started/setup_auth.md
    - get_started/setup_project.md
  - How to:
    - Workflow new issues: howto/workflow_new_item.md
    - Workflow existing issues: howto/workflow_existing_item.md
    - Workflow sprints: howto/workflow_sprints.md
    - Python scripting: howto/python_scripting.md
    - Shell completion: howto/command_completion.md
    - Connection problems: howto/connection_problems.md
  - Commands:
    - init: reference/manual/init.md
    - list: reference/manual/list.md
    - issue:
      - create: reference/manual/issue_create.md
      - close: reference/manual/issue_close.md
      - list: reference/manual/issue_list.md 
    - pr:
      - create: reference/manual/pr_create.md
      - close: reference/manual/pr_close.md
      - checkout: reference/manual/pr_checkout.md
      - list: reference/manual/pr_list.md
    - workon: reference/manual/workon.md
    - open: reference/manual/open.md
  - Config:
    - Config file: config/config_file.md
    - Using env vars: config/env_config.md
  - Discussion:
    - One Project Setup: discussion/oneproject_setup.md
    - contributing.md
    - discussion/upgrading.md

plugins:
  - search
  - macros:
        module_name: src/doing/utils

markdown_extensions:
    - abbr
    - meta
    - admonition
    - pymdownx.keys
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
          options:
              custom_icons:
                  - site/overrides/.icons
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
    - 'https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js'
    - 'assets/js/termynal.js'
    - 'assets/js/custom.js'

extra_css:
    - 'assets/css/termynal.css'
    - 'assets/css/custom.css'
