name: Unit tests
on: [pull_request]
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python  
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Static code checking with pyflakes
      run: |
        pip3 install ".[all]"
        pyflakes src
    - name: Run unit tests
      run: |
        pytest
