name: Unit tests
on: [pull_request]
jobs:
  run:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Static code checks with pre-commit hooks
        run: |
          pip3 install ".[all]"
          pre-commit run --all-files
      - name: Run unit tests
        run: |
          pytest
